// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvtnnetinzdwehgdhytc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12dG5uZXRpbnpkd2VoZ2RoeXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNTU3NDYsImV4cCI6MjA2NjgzMTc0Nn0.X83Ir64PS6Me6HeILqSRggiPd2c27OmpITRpJJ5jAxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});